sudo: required
services:
 - docker

before_install:
 - docker build -f Dockerfile.dev -t kaz/docker-react-demo .
 
script:
 - docker run -e CI=true kaz/docker-react-demo npm run test -- --coverage

deploy:
 - provider: elasticbeanstalk
 - region: us-west-2
 - app: "docker"
 - env: "docker-env"
 - bucker_name: "region_name_plus_path"
 - bucker_path: "docker"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: $AWS_SECRET_KEY
